# Generated by Django 4.1.3 on 2023-02-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
