# Generated by Django 4.1.3 on 2023-03-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagur', '0004_alter_comment_client_id_alter_favorite_client_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='client_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='client_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creator_id',
            new_name='owner',
        ),
    ]
