# Generated by Django 4.1.3 on 2023-03-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagur', '0005_rename_client_id_comment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='imagur.post', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
