# Generated by Django 4.1.3 on 2023-03-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagur', '0006_alter_favorite_post_id_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='imagur.post'),
        ),
    ]
